<?xml version="1.0"?>
<package format="3">
  <name>sky_rover</name>
  <version>0.0.1</version>
  <description>陆地天空双栖机器人（四旋翼 + 四轮）的 URDF 模型</description>
  <maintainer email="elac@example.com">elac</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>tf2_tools</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>